### ISSUE TITLE
blueprint 'sensor.other.lane_invasion' not found

### ISSUE THREAD

**Issue by chandanavgermany** [felipecode/coiltraine#23]
Some one please help with  this
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "view_model.py", line 91, in <module>
    carla09interface.game_loop(args, agent)
  File "/home/vaishu/opt/Self-Dri-Car-imi-2/coiltraine/model_view/carla09interface.py", line 818, in game_loop
    world = World(client.get_world(), hud)
  File "/home/vaishu/opt/Self-Dri-Car-imi-2/coiltraine/model_view/carla09interface.py", line 201, in __init__
    self.restart()
  File "/home/vaishu/opt/Self-Dri-Car-imi-2/coiltraine/model_view/carla09interface.py", line 256, in restart
    self.lane_invasion_sensor = LaneInvasionSensor(self.vehicle, self.hud)
  File "/home/vaishu/opt/Self-Dri-Car-imi-2/coiltraine/model_view/carla09interface.py", line 639, in __init__
    bp = world.get_blueprint_library().find('sensor.other.lane_invasion')
IndexError: blueprint 'sensor.other.lane_invasion' not found
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 50 (sensor.camera.rgb) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 51 (sensor.other.collision) 
terminate called without an active exception
Aborted (core dumped)

**Comment by chandanavgermany** [comment]
@felipecode do you know how to solve this??
