### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by aditya-xq** [felipecode/coiltraine#6]
This command `python3 tools/download_sample_models.py` raises the following error. (Rest of the commands provided in documentation until this one are working fine)

Downloading the coil models checkpoints  224 MB
Traceback (most recent call last):
  File "tools/download_sample_models.py", line 25, in <module>
    tf = tarfile.open("track2_baseline.tar.gz")
  File "/home/xq/anaconda3/envs/coiltraine/lib/python3.5/tarfile.py", line 1564, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Any idea how to resolve this?

**Comment by c0stya** [comment]
I have the same error. Are these files available with a direct link?

**Comment by buaalsy2003** [comment]
I have the same error. Please help!

**Comment by wangchangquan** [comment]
I have the same error. Please help!
